name    'dhgwilliam-innodb_buffer_pool_size'
version '0.0.2'
author 'dhgwilliam'
license 'Apache License, Version 2.0'
summary 'Adds custom fact to display MySQL innodb_buffer_pool_size setting'
description 'Adds custom fact to display MySQL innodb_buffer_pool_size setting'
project_page 'https://github.com/dhgwilliam/puppet-innodb_buffer_pool_size'
